### ISSUE TITLE
Remote Monitoring

### ISSUE THREAD

**Issue by franklinhares** [ToddGreenfield/homebridge-nut#12]
Can you monitor a remove nut server or must the server be running locally on the machine that homebridge is running on.

If you, how can you add a username a password for remote monitoring?

**Comment by ToddGreenfield** [comment]
Hi. The plugin monitors the nut client, not the server (where the UPS is hooked to). The client does need to be running on the homebridge machine. Check out this link for assistance setting up your nut server and client - http://wynandbooysen.com/raspberry-pi-ups-server-using-nut.html. It has all the information you would need including adding username/pswd for both server and client.

**Comment by franklinhares** [comment]
Unfortunately that link no longer works. I’m assuming all I need to do is get the client running on the machine hosting homebridge and I’ll be good to go.

**Comment by ToddGreenfield** [comment]
Give this one a try. https://melgrubb.com/2016/12/11/rphs-v2-ups/

**Comment by ToddGreenfield** [comment]
Another one to try- https://hackernoon.com/how-to-shutdown-your-servers-in-case-of-power-failure-ups-nut-co-34d22a08e92

**Comment by Ewarren7** [comment]
@franklinhares seems this will connect to a remote nuc server. I have nut server running on a pfsense and was very confused by this documentation although very glad this plugin exists. I just tried it pointing to pfsense server and it worked. 

No idea what username or password it is looking for. I have only setup the pfsnese nut server to work as a server to synology nut client which mandates using user `monuser` and password `secret` so I guess it works with that. 

For homebridge config I used the below. Polling was required from what I could tell otherwise the status would not update. 
```
{
    "platform": "Nut",
    "name": "Nut",
    "host": "[pfsense-ip]",
    "polling": "15"
}
```
